/* =====================================================================
   build.mjs — optional UMD bundle generator.
   Bundles src/infinite-flythrough.js into a browser-global IIFE so the
   demo also runs from file:// without any module server.
   Usage:  node scripts/build.mjs   → writes examples/infinite-flythrough.umd.js
   ===================================================================== */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(here, '..', 'src', 'infinite-flythrough.js'), 'utf8');

const body = src
  .replace(/export function createFlythrough/, 'function createFlythrough')
  .replace(/export default createFlythrough;?/, '')
  .replace(/export \{[^}]*\};?/g, '');

const umd = `/* infinite-flythrough.umd.js — generated by scripts/build.mjs (do not edit) */
(function (global) {
'use strict';
${body}
global.InfiniteFlythrough = { createFlythrough };
})(window);
`;

const out = join(here, '..', 'examples', 'infinite-flythrough.umd.js');
writeFileSync(out, umd, 'utf8');
console.log('UMD bundle written →', out, `(${(umd.length / 1024).toFixed(1)} KB)`);
